name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Function Dependencies
        run: npm install
        working-directory: ./functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}